### ISSUE TITLE
Getting error - cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by sankarkumar23** [SimplifyJobs/webpack-ext-reloader#120]
[ Starting the Hot Extension Reload Server... ]
Cannot read property 'tap' of undefined

I just installed the package and loaded the plugin like this. I am using create-react-app typescript project

const ExtReloader  = require('webpack-ext-reloader');

 entry: {
                    main: [env === 'development' &&
                        require.resolve('react-dev-utils/webpackHotDevClient'), paths.appIndexJs].filter(Boolean),
                    content: './src/chrome/content.ts',
                    background: './src/chrome/background.ts'
                },
                plugins: [
                    new **ExtReloader()],**
                output: {
                    ...webpackConfig.output,
                    filename: 'static/js/[name].js',
                },

**Comment by rushilsrivastava** [comment]
I think you are using webpack 4, and this project only supports version 5 and above. Please post a new issue following the template if you are still facing issues.

**Comment by sankarkumar23** [comment]
ok then.. please close the issue
