### ISSUE TITLE
Code in popup reloads but not content script

### ISSUE THREAD

**Issue by arnthors** [SimplifyJobs/webpack-ext-reloader#207]
**Type:**
  - [ ] bug
  - [ ] feature
  - [ ] enhancement
  - [x] question

**Environment:**
  - OS: macOS 12.2.1
  - Browser: Chrome
  - Library Version: 1.1.9

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Description:**
When updating my application code (the extension popup) it builds and the extension is auto reloaded in Chome.
However when updating my code in the content script it builds but the extension is not reloaded in Chrome; I have to update manually in `chrome://extensions` for the content script changes are recognized by Chrome.

1) Is this expected?
2) If not, any ideas or hints?

**Comment by rushilsrivastava** [comment]
I can't seem to reproduce this. Maybe this has to do with your config, could you share it?

**Comment by rushilsrivastava** [comment]
The same entry from your webpack config needs to be applied to `ExtReloader`. Your Dev config should be:

```
const ExtReloader = require('webpack-ext-reloader');
const config = require('./custom-webpack.config.js');

module.exports = devConfig => {
    const combinedConfig = config(devConfig);
    return {
        ...combinedConfig,
        plugins: [
            ...combinedConfig.plugins,
            new ExtReloader({
                reloadPage: true,
                entries: {
                    'content-script': './src/content-script.ts',
                    background: './src/background.ts',
                },
            }),
        ],
    };
};
```

**Comment by rushilsrivastava** [comment]
Hey - just reviewed this comment and edited my previous comment for the correct formatting. Apologize for the confusion!

**Comment by rushilsrivastava** [comment]
> Which sounds nice (although I can't seem to get it work but thats another matter) but I have a question. I'm also assuming I should fix my background reference, right?

Yeah, I missed this in my initial response. You should update your background reference.

> Another question: has this been tested with Typescript?

Yup! We use this internally with Typescript with no problems.
