### ISSUE TITLE
Support manifest comments

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [SimplifyJobs/webpack-ext-reloader#216]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**I'm going to open a PR:**
  - [x] yes (If you agree that this should be addressed.)
  - [ ] no

**Description:**

Both Chrome and Firefox state that comments are allowed in the manifest:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json
https://developer.chrome.com/docs/extensions/mv2/manifest/

Yet, they cause this project to crash.

As far as I can tell, you only read the manifest here: https://github.com/SimplifyJobs/webpack-ext-reloader/blob/master/src/utils/manifest.ts#L11

So it should be pretty simple and not add a lot of overhead to strip the comments there. 🙂

**Comment by rushilsrivastava** [comment]
This makes sense, and I would welcome a PR!

**Comment by s-h-a-d-o-w** [comment]
Damn, I missed that response back in March somehow. Sorry about that! 🙈

(Thanks for taking care of it - should be of help to my former colleagues.)
