### ISSUE TITLE
[CSP Issue] Refused to evaluate a string as JavaScript because 'unsafe-eval....

### ISSUE THREAD

**Issue by zchengb** [SimplifyJobs/webpack-ext-reloader#377]
👋 Hey guys, there is an issue that's been bothering me for a few days.
After I upgraded the Chrome extension Manifest version from v2 to v3. I got the CSP issue as the below error information. 

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*".
```

The target error content line lint at `background.js:1449` is `eval("\n\n//# sourceURL=webpack:///./background.js?");`

According to the error message, I have tried to add the specific Content Security Policy on the `manifest.json` file. But it doesn't work.

Please give me some advice if you have other solution ideas.

Thanks :)

**Comment by vialoh** [comment]
What is the `content_security_policy` in your `manifest.json`? It should look something like this:
```json
{
  "content_security_policy": {
    "extension_pages": "default-src 'self'; connect-src *"
  },
  "background": {
    "service_worker": "background.js"
  }
}
```

I'm going to close this issue but will continue replying if needed.
