### ISSUE TITLE
The webpack ext reloader does not work in the new version of webpack

### ISSUE THREAD

**Issue by 16bitcode** [SimplifyJobs/webpack-ext-reloader#494]
#### Describe the bug
Error reported when packaging files using hot update plugins, Error will be reported in background.js and cannot be used：
<img width="669" alt="image" src="https://github.com/SimplifyJobs/webpack-ext-reloader/assets/85008423/58572257-9f7a-4af8-864d-2839ea181c03">

The following is the usage configuration：
<img width="778" alt="image" src="https://github.com/SimplifyJobs/webpack-ext-reloader/assets/85008423/46b7603e-40d1-40a6-8848-1a2d8dbd1bb2">
<img width="756" alt="image" src="https://github.com/SimplifyJobs/webpack-ext-reloader/assets/85008423/6b391357-ea06-4ce1-ba6b-1e7962d7157d">
<img width="1214" alt="image" src="https://github.com/SimplifyJobs/webpack-ext-reloader/assets/85008423/01dd9e1e-f4ce-43f8-9ad4-287355e98fe8">

**Comment by tballard34** [comment]
I am having this issue as well

**Comment by vialoh** [comment]
@16bitcode @tballard34 I'm unable to repro the issue. What does your manifest look like? Or if you can provide a repo with the issue, that would be ideal.

**Comment by vialoh** [comment]
This _might_ be fixed in v1.1.13 which I will try to release ASAP. If it's still an issue, let me know with another comment on this issue and I will reopen.
