### ISSUE TITLE
When using ext reloader source maps in development mode are broken

### ISSUE THREAD

**Issue by tscislo** [SimplifyJobs/webpack-ext-reloader#507]
When using ext reloader **source maps** in development mode are broken.
I'm sure that ext reloader couses it because, when I disable ext reloader mapping between source code and bundled code is correct

I use webpack v4 and Extention Reloader v 1.1.12

Have you observed any issues with source maps generation in dev mode while using this reloader?

**Comment by vialoh** [comment]
Yes this is an issue. I'll see what I can do.
