### ISSUE TITLE
CVE in `useragent` dependency

### ISSUE THREAD

**Issue by lsmith77** [SimplifyJobs/webpack-ext-reloader#574]
[//]: # (These comments will not show up. You can keep them or delete them, up to you.)

#### Describe the bug

Security vulnerability in `useragent` dependency is unlikely to get fixed
https://github.com/3rd-Eden/useragent/issues/178

See also https://github.com/advisories/GHSA-mgfv-m47x-4wqp

Do you have any plans to address this? Potentially switching libraries?

**Comment by vialoh** [comment]
This particular vulnerability would apply only to Node.js servers. This webpack plugin runs only client-side as a browser extension in your development environment. Your input is appreciated, however!
