### ISSUE TITLE
The `manifest` option is not working if output.filename is not specified in webpack config

### ISSUE THREAD

**Issue by lmichelin** [SimplifyJobs/webpack-ext-reloader#91]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Ubuntu
  - Browser: N/A
  - Library Version: 1.1.8

**I'm going to open a PR:**
  - [ ] yes
  - [x] no

**Package options**
```js
new ExtReloader({
  reloadPage: true,
  manifest: "./src/manifest.json",
})
```

**Description:**
I was using webpack 4 and the [webpack-extension-reloader](https://github.com/rubenspgcavalcante/webpack-extension-reloader) package and it was working well without specifying `output.filename` in webpack config as the default behaviour (`"[name].js"`) was ok for me. I decided to migrate to webpack 5 and to use this library instead of webpack-extension-reloader, but to make it work I needed to specify explicitly `output.filename`  even if it's the default value.

If I don't specify the `output.filename` property, the `manifest` option is not working:

```
[webpack-cli] Error: 
    at Object.extractEntries (/home/xxxxxx/xxxxxxxxx/node_modules/webpack-ext-reloader/dist/webpack:/webpack-ext-reloader/src/utils/manifest.ts:21:11)
    at ExtensionReloaderImpl._registerPlugin (/home/xxxxxx/xxxxxxxxx/node_modules/webpack-ext-reloader/dist/webpack:/webpack-ext-reloader/src/ExtensionReloader.ts:93:9)
    at ExtensionReloaderImpl.apply (/home/xxxxxx/xxxxxxxxx/node_modules/webpack-ext-reloader/dist/webpack:/webpack-ext-reloader/src/ExtensionReloader.ts:128:12)
    at createCompiler (/home/xxxxxx/xxxxxxxxx/node_modules/webpack/lib/webpack.js:74:12)
    at /home/xxxxxx/xxxxxxxxx/node_modules/webpack/lib/webpack.js:44:48
    at Array.map (<anonymous>)
    at createMultiCompiler (/home/xxxxxx/xxxxxxxxx/node_modules/webpack/lib/webpack.js:44:33)
    at create (/home/xxxxxx/xxxxxxxxx/node_modules/webpack/lib/webpack.js:118:16)
    at webpack (/home/xxxxxx/xxxxxxxxx/node_modules/webpack/lib/webpack.js:135:47)
    at WebpackCLI.f [as webpack] (/home/xxxxxx/xxxxxxxxx/node_modules/webpack/lib/index.js:55:16)
```

Thanks for your support.

**Comment by rushilsrivastava** [comment]
Hey @lmichelin! Looking into this six months later, but better late than never, right? 😅 

I seem to be unable to reproduce this error - we use this internally without the `manifest` option as well, and it works just fine!

I threw together a test repository with the latest released version, [`v1.1.8`](https://www.npmjs.com/package/webpack-ext-reloader). Would it be possible to see your webpack config?

In the meantime, I am working on a new release, `1.2.0`, to address #90, so maybe you can test with that as well and see if that fixes it?

**Comment by rushilsrivastava** [comment]
I wasn't able to reproduce this error, take a look at the test repo [here](https://github.com/rushilsrivastava/test-webpack-ext-reloader). As you can see, we don't specify the `manifest` in the [`webpack.config.js`](https://github.com/rushilsrivastava/test-webpack-ext-reloader/blob/master/webpack.config.js) and this works as expected. 

I think this may be related to a different problem in your webpack config.

**Comment by rushilsrivastava** [comment]
I can't confirm whether not specifying `output.filename` worked in the previous versions or not, but this seems to be an intentional design choice and is not a bug. Ref: [v4](https://github.com/rubenspgcavalcante/webpack-extension-reloader/blob/master/src/utils/manifest.ts#L20-L22) vs [v5](https://github.com/SimplifyJobs/webpack-ext-reloader/blob/master/src/utils/manifest.ts#L15-L17).

This is an intentional design choice because we want to ensure that the output matches that of what is in the manifest. In the meantime, I've added a more helpful error message.
